### ISSUE TITLE
Generation of Callgraph

### ISSUE THREAD

**Issue by spanners** [florianschanda/miss_hit#217] opened 2021-06-16 15:43 UTC
**What kind of feature is this?**
* It would be useful to be able to generate a callgraph given a Matlab program as input.

**MISS_HIT component affected**
Choose one or more of the below:
* It doesn't look like this feature neatly fits into any of these categories as a separate entity.

**Describe the solution you'd like**
Given a collection of Matlab source files, output a callgraph (perhaps in GraphViz).

**Comment by florianschanda** [comment] 2021-06-17 10:12
This is a duplicate of #155 so I am closing this.

Just to manage expectations, this will be *hard* because of the insanity of MATLAB's type system, so it will not happen soon. There is a few things that I need to do first:
* full semantic analysis, type resolution, inference and synthesis
* enough interpretation so that I can build an abstract interpretation for your program that deals with all the polymorphism and function pointers

There is a reason the Mathworks supplied tool for callgraphs does not work :/

**Closed by florianschanda** 2021-06-17 10:12 UTC
Labels: duplicate
