### ISSUE TITLE
New rule: "Whitespace before ..." 

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#10] opened 2019-11-28 09:56 UTC
Line continuation (...) should always be preceded by a whitespace in code

Example
```
x = a + b +...
    c + d
```
should instead be
```
x = a + b + ...
    c + d
```

**Comment by florianschanda** [comment] 2019-11-28 10:53
Duplicate of #12 (more or less)

**Closed by florianschanda** 2019-11-28 10:53 UTC
Labels: duplicate, enhancement
